### ISSUE TITLE
ESX COMPATIBLE

### ISSUE THREAD

**Issue by hasidu** [BerkieBb/eol_factions#2]
Hi this is nice script and very useful one 

i wondering that as this script for qbcore so can you also convert it to work with esx pls ?

**Comment by BerkieBb** [comment]
I've gotten everything converted, besides the money part, using esx_addonaccount you have to make the balances in the database and there is no export, which means everytime someone makes a new faction, a server restart has to happen for them to be able to see their balance, would you have an idea on how to mitigate this issue?

**Comment by hasidu** [comment]
nice to hear that you were able to make this work with esx 


so for the money problem i think most of resource has this problem but it's ok restart.

is there way you can disable everyone can make factions like only who have permmions one config can make factions ?

or on config can you make like if everyone can make faction = true (anyone can make factions) if everyone can make faction = false (only who have permission on config can make factions ) ?

**Comment by hasidu** [comment]
hi how is it going ?

**Comment by BerkieBb** [comment]
Going to rework the resource to only be standalone, framework support can be added by yourself but only needed for money management
