### ISSUE TITLE
it comes up with this error 

### ISSUE THREAD

**Issue by CJ2028** [BerkieBb/eol_factions#3]
[script:eol_factions-] SCRIPT ERROR: @eol_factions-main/server.lua:393: eol_factions-main was unable to execute a query!
[script:eol_factions-] Query: INSERT INTO `management_funds` (`job_name`, `amount`, `type`) VALUES (?, ?, ?)
[script:eol_factions-] ["The Vipers",0,"gang"]
[script:eol_factions-] Table 'zap1155365-1.management_funds' doesn't exist
[script:eol_factions-] > createFaction (@eol_factions-main/server.lua:393)
[script:eol_factions-] > handler (@eol_factions-main/server.lua:757)
[script:eol_factions-] > logError (@oxmysql/dist/build.js:26272)
[script:eol_factions-] > rawQuery (@oxmysql/dist/build.js:26447)
[script:eol_factions-] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:eol_factions-] SCRIPT ERROR: @eol_factions-main/framework.lua:32: attempt to index a nil value (local 'player')

what can i do?

**Comment by BerkieBb** [comment]
Your database is not setup (correctly). Seeing as you have a zap server, you should ask them to fix that if they installed your framework for you

**Comment by BerkieBb** [comment]
Also, do remove the `-main` from the name

**Comment by CJ2028** [comment]
how would i fix that i did remove alot of the resources they put in, do u thik that could be it?

**Comment by BerkieBb** [comment]
That doesn't affect the database

**Comment by CJ2028** [comment]
hmmmmm theres no way i can fix it?

**Comment by CJ2028** [comment]
also I got the qbcore  by a txadmin template

**Comment by CJ2028** [comment]
i tried it again 
and i just got this?
SCRIPT ERROR: @eol_factions/framework.lua:32: attempt to index a nil value (local 'player')

**Comment by BerkieBb** [comment]
Rework coming which removes this sql and going to convert to standalone only
